version: "3.9"

services:
  mongo:
    image: "mongo:6.0.5"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - ../docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ../mongodb-dump/:/tmp/mongodb-dump
    healthcheck:
      test: [ "CMD","mongosh", "-u", "root", "-p", "password", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
  growthbook:
    image: "growthbook/growthbook:2.0.0"
    ports:
      - "3000:3000"
      - "3100:3100"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - MONGODB_URI=mongodb://root:password@mongo:27017/
  db-sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: Password1
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Password1" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
  app:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    env_file: .env.development
    depends_on:
      db-sql-server:
        condition: service_healthy
    volumes:
      - "./:/app/"
    ports:
      - "5238:80"
    working_dir: /app
    command: "/app/scripts/start.sh"
