version: "3.9"

services:
  remote-interpreter-mariadb:
    build:
      context: .
    env_file: .env.mariadb
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db-mariadb:
        condition: service_healthy
  db-mariadb:
    image: mariadb:11
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: "development"
      MARIADB_ROOT_PASSWORD: "root"
    volumes:
      - ./mariadb-docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      interval: 2s
      timeout: 1m
      retries: 5
      start_period: 10s
  terminal-mariadb:
    image: mariadb:11
    command: [ "bash" ]

  remote-interpreter-postgresql:
    build:
      context: .
    env_file: .env.postgresql
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db-postgresql:
        condition: service_healthy
  db-postgresql:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./postgresql-docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "--dbname=postgres",
          "--username=postgres"
        ]
      interval: 2s
      timeout: 1m
      retries: 5
      start_period: 10s
  terminal-postgresql:
    image: postgres:16
    command: [ "bash" ]

  remote-interpreter-sqlserver:
    build:
      context: .
    env_file: .env.sqlserver
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db-sqlserver:
        condition: service_healthy
  db-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "T@R63dis"
      MSSQL_TCP_PORT: 1433
      # Developer / Express / Standard / Enterprise  / EnterpriseCore
      MSSQL_PID: Developer
      ACCEPT_EULA: "Y"
      # Custom
      DB_DATABASE: development
    volumes:
      - ./sqlserver-docker-entrypoint-initdb.d:/usr/src/app/
    command: "/usr/src/app/restore-backup-and-start-sqlserver.sh"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -d "$$DB_DATABASE" -U sa -P "$$MSSQL_SA_PASSWORD" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
