apiVersion: v1
kind: Service
metadata:
  namespace: support-tools
  name: db-postgres-service
spec:
  selector:
    app: db-postgres
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      # See `kind-config.yaml` to understand why I configured port 30000!
      nodePort: 30000
      port: 5432
      targetPort: db-socket-port

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-postgres-deployment
  namespace: support-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-postgres
  template:
    metadata:
      labels:
        app: db-postgres
    spec:
      containers:
        - name: db-postgres
          image: postgres:13.2-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - name: db-socket-port
              containerPort: 5432
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
