apiVersion: v1
kind: Service
metadata:
  namespace: development
  name: db-postgres-service
spec:
  selector:
    app: db-postgres
    tier: db
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      # See `kind-config.yaml` to understand why I configured port 30000!
      nodePort: 30000
      port: 5432
      targetPort: db-socket-port

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-postgres-deployment
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-postgres
      tier: db
  template:
    metadata:
      labels:
        app: db-postgres
        tier: db
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: db-postgres-configmap
      containers:
        - name: db-postgres
          image: postgres:15-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: featuretoggle
            - name: POSTGRES_USER
              value: unleash
            - name: POSTGRES_PASSWORD
              value: jasmine
          ports:
            - name: db-socket-port
              containerPort: 5432
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: config-volume
              mountPath: /docker-entrypoint-initdb.d/unleash-db.dump.sql
              subPath: unleash-db.dump.sql
              readOnly: true
