apiVersion: v1
kind: ConfigMap
metadata:
  namespace: development
  name: locust-configmap
data:
  UNLEASH_API_ADMIN_TOKEN: "*:*.4b578b55ae9e95e9c11a3214d5cdcce1e3d6f15c3d865ec259e2eeeb"
  UNLEASH_URL: "http://unleash-service.development.svc.cluster.local:4242"
  LOCUST_LOCUSTFILE: "load_testing_unleash_locust/locustfile.py"

---

kind: Service
apiVersion: v1
metadata:
  namespace: development
  name: locust-master
  labels:
    app: locust-master
spec:
  ports:
    - port: 5557
      targetPort: master-p1
      protocol: TCP
      name: master-p1
    - port: 5558
      targetPort: master-p2
      protocol: TCP
      name: master-p2
  selector:
    app: locust-master
    tier: web

---

kind: Service
apiVersion: v1
metadata:
  namespace: development
  name: locust-master-ui
  labels:
    app: locust-master
spec:
  ports:
    - port: 8089
      targetPort: master-web
      protocol: TCP
      # See `kind-config.yaml` to understand why I configured port 30100!
      nodePort: 30100
      name: master-web
  selector:
    app: locust-master
    tier: web
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: development
  name: locust-master
  labels:
    name: locust-master
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
      tier: web
  template:
    metadata:
      labels:
        app: locust-master
        tier: web
    spec:
      containers:
        - name: locust-master
          image: load-testing-unleash-locust_performance-testing
          imagePullPolicy: IfNotPresent
          env:
            - name: LOCUST_MODE_MASTER
              value: "true"
          envFrom:
            - configMapRef:
                name: locust-configmap
          ports:
            - name: master-web
              containerPort: 8089
              protocol: TCP
            - name: master-p1
              containerPort: 5557
              protocol: TCP
            - name: master-p2
              containerPort: 5558
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 384Mi
