version: "3.8"

services:
  product-a:
    build:
      context: product_a
    ports:
      - "8000:8000"
  product-b:
    build:
      context: product_b
    ports:
      - "8001:8001"
  functional-testing:
    build:
      context: functional_testing
    environment:
      DOWNLOAD_CHROME: "False"
      ENABLE_VIRTUAL_DISPLAY: "True"
      SELENIUM_TAKE_SCREENSHOT: "True"
      SELENIUM_SCREENSHOTS_FOLDER: "/tmp/screenshots"
      SELENIUM_IMPLICIT_WAIT: 5
      # Remember! I'm using an internal NGINX to translate both addresses!
      # Know more here: https://www.willianantunes.com/blog/2021/11/sso-with-cognito-through-the-authorization-code-grant-type/
      PRODUCT_A_URL: "http://localhost:8000"
      PRODUCT_B_URL: "http://localhost:8001"
    volumes:
      # You should create "screenshots" with proper settings
      # Something to guide you:
      # If you execute `id` in the container you'll receive: uid=1200(seluser) gid=1201(seluser) groups=1201(seluser),27(sudo)
      # Then you should create a folder with the following: mkdir screenshots && sudo chown -R 1200 screenshots
      - ./screenshots:/tmp/screenshots
