version: "3.8"

services:
  product-a:
    build:
      context: product_a
    ports:
      - "8000:8000"
  product-b:
    build:
      context: product_b
    ports:
      - "8001:8001"
  functional-testing:
    build:
      context: functional_testing
    environment:
      DOWNLOAD_CHROME: "False"
      ENABLE_VIRTUAL_DISPLAY: "True"
      SELENIUM_TAKE_SCREENSHOT: "True"
      SELENIUM_SCREENSHOTS_FOLDER: "/tmp/screenshots"
      PRODUCT_A_URL: "http://product-a:8000"
      PRODUCT_B_URL: "http://product-b:8001"
    volumes:
      # You should create "screenshots" with proper settings
      - ./screenshots:/tmp/screenshots
